### ISSUE TITLE
Is it possible to just use amqpserver as standlone mock server?

### ISSUE THREAD

**Issue by coding-yogi** [NeowayLabs/wabbit#16]
We have some microservices written in Python and Scala and I am searching for a mock implementation of RabbitMQ. I was wondering if amqpserver can be used as standalone.
But looking at the code I do not think its a possibility. Could you please confirm?

**Comment by tiago4orion** [comment]
@coding-yogi  Sorry for the late reply.. Yeah, it could be used only from inside go (it's a go library).
