### ISSUE TITLE
Cannot Dial with streadway/amqp

### ISSUE THREAD

**Issue by fbiville** [NeowayLabs/wabbit#41]
It seems the latest version (`v0.0.0-20200409220312-12e68ab5b0c6`) of wabbit does not work with streadway/amqp (`v1.0.0`). Here is a simple example ([link to repo](https://github.com/fbiville/wabbit-bug/)):

```golang
package connections_test

import (
	"github.com/NeowayLabs/wabbit/amqptest/server"
	"github.com/streadway/amqp"
	"gotest.tools/assert"
	"testing"
)

func TestDial(t *testing.T) {
	url := "amqp://localhost:5672/%2f"
	amqpServer := server.NewServer(url)
	assert.NilError(t, amqpServer.Start())
	defer stopServer(t, amqpServer)

	connection, err := amqp.Dial(url)

	assert.NilError(t, err)
	defer closeConnection(t, connection)
	assert.Check(t, connection != nil)
}

func stopServer(t *testing.T, amqpServer *server.AMQPServer) {
	assert.NilError(t, amqpServer.Stop())
}

func closeConnection(t *testing.T, connection *amqp.Connection) {
	assert.NilError(t, connection.Close())
}

```

This results in: 
```
=== RUN   TestDial
    TestDial: connection_test.go:18: assertion failed: error is not nil: dial tcp 127.0.0.1:5672: connect: connection refused
--- FAIL: TestDial (0.01s)
FAIL
```

**Comment by fbiville** [comment]
Even with the last commit passing CI (25d9d0dfe3b9), I get the same error.

**Comment by maxrem** [comment]
Hi you should't use `"github.com/streadway/amqp"` for this. Also, use the `amqptest` package to create a mock connection e.g. `amqptest.Dial("amqp://localhost:5672/%2f")`

**Comment by fbiville** [comment]
Thanks for the reply.

In my case, the implementation does the `Dial` call, so I cannot really replace it.
One way to accommodate this limitation would be to introduce a `DialFunc` parameter maybe, but that's an extra complication imo.

Maybe I misread [this particular example](https://github.com/knative-sandbox/eventing-rabbitmq/blob/master/source/pkg/adapter/adapter_test.go#L118), as I thought just started a fake server was sufficient.

**Comment by i4ki** [comment]
Hi @fbiville,

You should use `wabbit/amqp` in the implementation and `wabbit/amqptest` for the tests.
The idea is that both packages return the same [interface](https://github.com/NeowayLabs/wabbit/blob/master/amqp.go#L18), then if you only pass the interface around you can easily test your functions by passing the mocked version during the test (amqptest).

In other words: In the real implementation you import `wabbit/amqp` and call `amqp.Dial()` and pass the interfaces around (amqp.Channel and so on). On tests, you import `wabbit/amqptest` and connect to the mock server by calling `amqptest.Dial()` that returns the same interface, then you can pass it to the functions you wanna test.

There's no way to use this library by importing and using `streadway/amqp` directly.

Let me know if this helps.

**Comment by fbiville** [comment]
Thanks for the clarification, it helps indeed!
