### ISSUE TITLE
Support for Go 1.6

### ISSUE THREAD

**Issue by lucasgomide** [NeowayLabs/wabbit#7]
@tiago4orion  The [build](https://travis-ci.org/NeowayLabs/wabbit/builds/210049299) on travis have fails 'cuz can not import go-dockerclient.

Looking for `go-dockerclient` lib, I just figured out that the support for Go 1.6 was [removed] (https://github.com/fsouza/go-dockerclient/commit/597128c3e24917d9dd6c47867b902cef3532fc24). There are no tags more, so we cannot use gopkg ):

Let's remove the support for older go versions too ? 

What do you think?

**Comment by tiago4orion** [comment]
Yes, makes sense.

Can you change the .travis.yml of your branch to build go >= 1.7?

```ỳml
go:
  - tip
  - 1.8
  - 1.7
```

Thank you for your help!

**Comment by lucasgomide** [comment]
Yeah ! 

I'll do it asap
